// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_q2mnpx4n8DrC-ffgjfqAET4_HMORWtA',
    appId: '1:525502946293:web:9030bd3f48b38848aa9ebc',
    messagingSenderId: '525502946293',
    projectId: 'gimmic-gyudon',
    authDomain: 'gimmic-gyudon.firebaseapp.com',
    storageBucket: 'gimmic-gyudon.appspot.com',
    measurementId: 'G-ZH2XRNGHWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7d_k_bV0dvq0tWlidxK6NzdyMe3jZus',
    appId: '1:525502946293:android:63eac8b71376de8daa9ebc',
    messagingSenderId: '525502946293',
    projectId: 'gimmic-gyudon',
    storageBucket: 'gimmic-gyudon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnQVKfMVEnwCqgIpwyi1P2fkJ3ej4ZlE',
    appId: '1:525502946293:ios:57faba9e5024a4bcaa9ebc',
    messagingSenderId: '525502946293',
    projectId: 'gimmic-gyudon',
    storageBucket: 'gimmic-gyudon.appspot.com',
    iosClientId: '525502946293-9vkptt776t255qh1sv8vekvmumslf8fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gimmic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvnQVKfMVEnwCqgIpwyi1P2fkJ3ej4ZlE',
    appId: '1:525502946293:ios:57faba9e5024a4bcaa9ebc',
    messagingSenderId: '525502946293',
    projectId: 'gimmic-gyudon',
    storageBucket: 'gimmic-gyudon.appspot.com',
    iosClientId: '525502946293-9vkptt776t255qh1sv8vekvmumslf8fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gimmic',
  );
}
